#!/usr/bin/env bash

# HELP as-service-user <service-username> <commands...>; execute commands as a service user

as-service-user () (
    # username and command must be given
    _echo debug "as-systemd-service-user $1 $2"
    [[ $# != 2 ]] && exit 1
    sudo machinectl shell "$1@" $(whereis bash | awk '{ printf $2 }') -c "$2"
)

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && as-service-user "$@"
