#!/usr/bin/env bash

# HELP echo debug/important/status/success/unexpected txt

main () (
    arg="$1"
    case "$arg" in
        -h|--help)
            show-usage
            exit 0
            ;;
        debug)
            [[ -z "${DEBUG_SETUP_ON}" ]] && exit
            tput setaf 5
            echo "[DEBUG] [$(date +"%H:%M:%S")] ${@:2}"
            tput sgr0

            echo "[DEBUG] ${@:2}" | systemd-cat --identifier="setup.sh" --priority="notice"
            exit
            ;;
        important)
            tput setaf 3 # yellow
            tput bold
            echo "[IMPORTANT] [$(date +"%H:%M:%S")] ${@:2}"
            tput sgr0

            echo "[IMPORTANT] ${@:2}" | systemd-cat --identifier="setup.sh" --priority="notice"
            exit
            ;;
        status)
            tput setaf 6 # cyan
            echo "[STATUS] [$(date +"%H:%M:%S")] ${@:2}"
            tput sgr0

            echo "[STATUS] ${@:2}" | systemd-cat --identifier="setup.sh" --priority="notice"
            exit
            ;;
        success)
            tput setaf 2 # green
            tput bold
            echo "[SUCCESS] [$(date +"%H:%M:%S")] $@"
            tput sgr0

            echo "[SUCCESS] ${@:2}" | systemd-cat --identifier="setup.sh" --priority="notice"
            exit
            ;;
        unexpected)
            tput setaf 1 # red
            tput bold
            echo "[UNEXPECTED] [$(date +"%H:%M:%S")] ${@:2}"
            tput sgr0

            echo "[UNEXPECTED] ${@:2}" | systemd-cat --identifier="setup.sh" --priority="err"
            exit
            ;;
        *)
            echo "Unknown 'main' argument: $arg"
            exit 2
            ;;
    esac
)

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
